name: Publish Package
on:
  release:
    types:
      - created
# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read      # Required to clone the repo.
      packages: write     # Required to publish to GitHub Packages with NODE_AUTH_TOKEN (GITHUB_TOKEN).
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/
          scope: '@newfold-labs'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
